import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join, relative, extname } from 'path'

const DIST_GUI = join(process.cwd(), 'dist', 'gui')
const OUTPUT = join(process.cwd(), 'src', 'server', 'embeddedAssets.ts')

const TEXT_EXTENSIONS = new Set(['.html', '.js', '.mjs', '.cjs', '.css', '.json', '.svg', '.map'])

function walk(dir: string, files: Array<{ path: string; content: string; isBase64: boolean }> = []) {
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)
    if (stat.isDirectory()) {
      walk(fullPath, files)
    } else {
      const relPath = '/' + relative(DIST_GUI, fullPath).replace(/\\/g, '/')
      const ext = extname(fullPath)
      const isText = TEXT_EXTENSIONS.has(ext)
      if (isText) {
        files.push({ path: relPath, content: readFileSync(fullPath, 'utf-8'), isBase64: false })
      } else {
        files.push({ path: relPath, content: readFileSync(fullPath).toString('base64'), isBase64: true })
      }
    }
  }
  return files
}

function main() {
  try {
    statSync(DIST_GUI)
  } catch {
    console.log('[embedGuiAssets] dist/gui not found, skipping')
    const emptyModule = `// Auto-generated by scripts/embedGuiAssets.ts\nexport const EMBEDDED_ASSETS: Record<string, { content: string; isBase64: boolean }> = {}\n`
    writeFileSync(OUTPUT, emptyModule)
    return
  }

  const files = walk(DIST_GUI)
  const entries = files
    .map((f) => {
      const escapedContent = f.content
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
      return `  '${f.path}': { content: '${escapedContent}', isBase64: ${f.isBase64} }`
    })
    .join(',\n')

  const moduleSrc = `// Auto-generated by scripts/embedGuiAssets.ts
// Do not edit manually

export const EMBEDDED_ASSETS: Record<string, { content: string; isBase64: boolean }> = {
${entries}
}
`
  writeFileSync(OUTPUT, moduleSrc)
  console.log(`[embedGuiAssets] Embedded ${files.length} files from dist/gui`)
}

main()
